slam_toolbox:
  ros__parameters:
    use_sim_time: false

    scan_queue_size: 10
    minimum_time_interval: 0.0

    map_frame: map
    odom_frame: odom
    base_frame: base_link

    scan_topic: "/scan"

    use_scan_matching: true
    use_odom: true

    mode: mapping