#!/bin/bash
# Quick Start for Monitoring Rover Movement

echo ""
echo "🚗 ROVER MONITORING - QUICK START"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "STEP 1: Terminal 1 - Start Navigation System"
echo "─────────────────────────────────────────────"
echo "  cd ~/ros2_ws"
echo "  source install/setup.bash"
echo "  ros2 launch rover_navigation full_navigation.launch.py"
echo ""
echo ""
echo "STEP 2: Terminal 2 - Monitor Rover Movement"
echo "─────────────────────────────────────────────"
echo "  cd ~/ros2_ws"
echo "  source install/setup.bash"
echo "  python3 monitor_rover.py"
echo ""
echo "  ✓ Shows live position (X, Y)"
echo "  ✓ Shows heading angle"
echo "  ✓ Shows velocity commands"
echo "  ✓ Shows planning status"
echo ""
echo ""
echo "STEP 3: Terminal 3 - Send Goal to Rover"
echo "─────────────────────────────────────────"
echo "  ros2 topic pub -1 /goal geometry_msgs/PoseStamped '"
echo "  {header: {frame_id: \"odom\"}, "
echo "   pose: {position: {x: 10.0, y: 5.0, z: 0.0}, "
echo "          orientation: {w: 1.0}}}"
echo "  '"
echo ""
echo ""
echo "OPTIONAL: Terminal 4 - Visual Display (RViz)"
echo "──────────────────────────────────────────────"
echo "  ros2 run rviz2 rviz2"
echo ""
echo "  Then in RViz:"
echo "    • Set Fixed Frame: odom"
echo "    • Add PoseStamped: /odom (blue arrow = robot)"
echo "    • Add Path: /path (red line = planned path)"
echo "    • Add LaserScan: /scan (white dots)"
echo "    • Add OccupancyGrid: /occupancy_grid (obstacles)"
echo ""
echo "═══════════════════════════════════════════════════════"
