amcl:
  ros__parameters:
    use_sim_time: false
    min_particles: 500
    max_particles: 2000
    kld_err: 0.01
    kld_z: 0.99
    update_min_d: 0.1
    update_min_a: 0.1

planner_server:
  ros__parameters:
    expected_planner_frequency: 1.0

controller_server:
  ros__parameters:
    controller_frequency: 20.0
    # using DWB controller by default; tune in controller params as needed

local_costmap:
  ros__parameters:
    update_frequency: 5.0
    publish_frequency: 2.0
    global_frame: odom
    robot_base_frame: base_link
    width: 6.0
    height: 6.0
    resolution: 0.05
    rolling_window: true
    plugins: ["obstacle_layer", "inflation_layer"]
    obstacle_layer:
      observation_sources: scan
      scan: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
    inflation_layer:
      inflation_radius: 0.5

global_costmap:
  ros__parameters:
    update_frequency: 1.0
    publish_frequency: 1.0
    global_frame: map
    robot_base_frame: base_link
    width: 20.0
    height: 20.0
    resolution: 0.05
    rolling_window: false
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
    static_layer:
      map_subscribe_transient_local: true
    obstacle_layer:
      observation_sources: scan
      scan: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
    inflation_layer:
      inflation_radius: 0.5
